const AUTH_LOCAL_STORAGE_KEY = 'access_token'
const INFO_USER_LOCAL_STORAGE_KEY = 'info_user'
const TOKEN_FORGOT_PASS = 'token_forgot_pass'
const TOKEN_VERIFY_CODE = 'token_verify_code'

export {AUTH_LOCAL_STORAGE_KEY, INFO_USER_LOCAL_STORAGE_KEY, TOKEN_FORGOT_PASS, TOKEN_VERIFY_CODE}
